# 1.Create a 3x3x3 array with random values using numpy

In [3]:
import numpy as np

array_3x3x3 = np.random.rand(3, 3, 3)

print (array_3x3x3)


[[[0.40686263 0.3105857  0.53541663]
  [0.73910527 0.85156568 0.56248259]
  [0.2356392  0.06589492 0.5763424 ]]

 [[0.91903713 0.62567429 0.38494436]
  [0.63388618 0.278327   0.27334822]
  [0.00857764 0.10688649 0.46706461]]

 [[0.94745922 0.01185644 0.4033047 ]
  [0.00487848 0.19499925 0.85291651]
  [0.16080167 0.35945091 0.25120414]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [4]:
import numpy as np

matrix = np.zeros((5, 5))

np.fill_diagonal(matrix[1:], [1, 2, 3, 4])

print(matrix)


[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern.

In [5]:
import numpy as np

matrix = np.zeros((8, 8), dtype=int)

matrix[::2, ::2] = 1

matrix[1::2, 1::2] = 1

print(matrix)


[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


# 4.Normalize a 5 * 5 random matrix

In [6]:
import numpy as np

random_matrix = np.random.rand(5, 5)

max_value = random_matrix.max()

normalized_matrix = random_matrix / max_value

print("Original matrix:")
print(random_matrix)

print("\nNormalized matrix:")
print(normalized_matrix)


Original matrix:
[[0.38999573 0.87996604 0.35594942 0.66242398 0.46494793]
 [0.09883162 0.00569078 0.24689009 0.19873564 0.02814585]
 [0.17047443 0.7182126  0.95970795 0.01133439 0.73201677]
 [0.33824518 0.50706955 0.16903868 0.31685937 0.88770429]
 [0.46214356 0.55877637 0.39813118 0.31693121 0.15643372]]

Normalized matrix:
[[0.40636918 0.91691023 0.37089348 0.69023496 0.48446815]
 [0.10298093 0.0059297  0.25725543 0.20707928 0.02932752]
 [0.17763157 0.74836579 1.         0.01181025 0.76274951]
 [0.35244595 0.52835818 0.17613554 0.33016229 0.92497336]
 [0.48154604 0.58223585 0.41484619 0.33023714 0.16300138]]


# 5.How to find common values between two arrays?

In [7]:
import numpy as np

array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([8, 4, 6, 5, 7])

common_values = np.intersect1d(array1, array2)

print(common_values)

[4 5]


# 6.How to get the dates of yesterday, today and tomorrow?

In [8]:
import numpy as np
import datetime

current_date = datetime.date.today()

yesterday = current_date - datetime.timedelta(days=1)
today = current_date
tomorrow = current_date + datetime.timedelta(days=1)

print("Yesterday:", yesterday)
print("Today:", today)
print("Tomorrow:", tomorrow)

Yesterday: 2023-09-20
Today: 2023-09-21
Tomorrow: 2023-09-22


# 7.Consider two random array A and B, check if they are equal 

In [9]:
import numpy as np

A = np.array([1, 2, 3])
B = np.array([1, 2, 3])

if np.array_equal(A, B):
    print("Arrays A and B are equal.")
else:
    print("Arrays A and B are not equal.")


Arrays A and B are equal.


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [11]:
import numpy as np

random_vector = np.random.rand(10)

max_index = np.argmax(random_vector)

random_vector[max_index] = 0

print("Random vector with the maximum value replaced by 0:")
print(random_vector)

Random vector with the maximum value replaced by 0:
[0.29405766 0.48347305 0.38357543 0.3793269  0.73762789 0.03884164
 0.15995788 0.7346398  0.69089051 0.        ]


# 9.How to print all the values of an array 

In [13]:
import numpy as np

my_array = np.array([10, 20, 30, 40, 50])

my_list = my_array.tolist()

print(my_list)

[10, 20, 30, 40, 50]


# 10.Subtract the mean of each row of a matrix

In [14]:
import numpy as np

matrix = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

row_means = np.mean(matrix, axis=1, keepdims=True)

result_matrix = matrix - row_means

print(result_matrix)

[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?

In [21]:
import numpy as np

first_vector = np.array([1, 2, 3, 4, 5])

second_vector = np.array([1, 4, 4])

result_vector = np.zeros_like(first_vector)

result_vector[second_vector] += 1

result_vector += first_vector

print(result_vector)


[1 3 3 4 6]


# 12.How to get the diagonal of a dot product?

In [22]:
import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

dot_product = np.dot(A, B)

diagonal = np.diag(dot_product)

print(diagonal)

[30 69 90]


# 13.How to find the most frequent value in an array ?

In [24]:
import numpy as np

array = np.array([10,20,40,30,50,40,30,10,40])
counts = np.bincount(array)
most_frequent_value = np.argmax(counts)

print("The most frequent value is:", most_frequent_value)


The most frequent value is: 40


# 14.How to get the n largest values of an array

In [25]:
import numpy as np

arr = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5, 3])

n = 3

partitioned_arr = np.partition(arr, -n)

n_largest_elements = partitioned_arr[-n:]

print("The", n, "largest elements are:", n_largest_elements)


The 3 largest elements are: [5 6 9]


# 15.How to create a record array from a regular array 

In [1]:
import numpy as np

regular_array = np.array([1,2,3,4,5])

record_array = np.rec.array(regular_array,dtype=[('my_column',int)])

print("Record Array:")   
print(record_array) 
print("Accessing 'my_coulmn':",record_array.my_column)  


Record Array:
[(1,) (2,) (3,) (4,) (5,)]
Accessing 'my_coulmn': [1 2 3 4 5]


# 16.How to swap two rows of an array

In [31]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

row1_index = 0  
row2_index = 2  

arr[row1_index], arr[row2_index] = arr[row2_index].copy(), arr[row1_index].copy()

print(arr)


[[7 8 9]
 [4 5 6]
 [1 2 3]]


# 17.Write python code to reshape to the next dimension of numpy array 

In [32]:
import numpy as np

original_array = np.array([1, 2, 3, 4, 5, 6])

reshaped_array = original_array.reshape(-1, 2)  

print("Original Array:")
print(original_array)
print("\nReshaped Array:")
print(reshaped_array)

Original Array:
[1 2 3 4 5 6]

Reshaped Array:
[[1 2]
 [3 4]
 [5 6]]
